[package]
name = "indexed_bitvec"
version = "0.1.0"
authors = ["DarkOtter <>"]

[dependencies]
byteorder = "1"

[dev-dependencies]
quickcheck = "0.6"

[profile.release]
lto = true
codegen-units = 1
incremental = false
