[package]
name = "indexed_bitvec"
version = "0.1.0"
authors = ["DarkOtter <>"]
license = "Apache-2.0"

[dependencies]
byteorder = "1"

[dev-dependencies]
rand = "0.4"
quickcheck = "0.6"

[profile.release]
lto = true
codegen-units = 1
incremental = false
